### ISSUE TITLE
一些说法

### ISSUE THREAD

**Issue by wulintang** [gaojunxin/yunque-qimen#1]
小道刚刚测试了一下，尚可。不过有个弊端，你的太极在逆转。

**Comment by gaojunxin** [comment]
> 小道刚刚测试了一下，尚可。不过有个弊端，你的太极在逆转。

🙏感谢道长的反馈，后面优化下这个。

**Comment by gaojunxin** [comment]
@wulintang 已经修改太极转动方向

**Comment by wulintang** [comment]
太极不仅是逆转，整个都是镜像的。我给你个示例
https://cdn.wulintang.net/taiji/
这是我的一个预加载页面，你看看太极的转向and方向。
